prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG

.storybook/main.ts
관련 이슈: https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/issues/7
- 스토리북에서 절대경로 @사용하게 설정
<br>
- storybook폴더의 main.ts에 스토리북 절대경로 @ 사용하게 처리했어요
- https://stackoverflow.com/questions/66444895/how-to-resolve-aliases-in-storybook
<br>
설정을 안해주었을 경우
설정을 해주었을 경우
=> 🐛 스토리북 절대 경로 설정

src/app/api/posts/create/route.ts, src/components/molcules/file-picker/index.tsx, src/components/templates/NewPostPageTemplate/NewPostPageTemplate.tsx, src/hooks/useUploadForm.ts, src/lib/axios.ts, src/services/post/index.ts
관련 이슈: #76
<br>
- base64 인코딩 안하는걸로 원복했습니다.
- 이미지 정상 업로드 확인, form 데이터를 주고받도록 설정
- formData나 Image 처리를 제대로 안 해봐서 삽질했네요... 이번 기회에 배워갑니다. 그리고 효중님께 심심한 사과말씀...
- Post의 예시를 첨부하오니 참고해주세요.
```json
{
"likes": [],
"comments": [],
"_id": "650308a4b888c17b6e4cafb3",
"title": "{\"title\":\"ㄹㅇㅋㅋㅋ\",\"description\":\"<p>ㅇㄹ</p>\"}",
"image": "https://res.cloudinary.com/learnprogrammers/image/upload/v1694697635/post/f1e33b68-55ce-431e-9df3-d4c593fcec53.jpg",
"imagePublicId": "post/f1e33b68-55ce-431e-9df3-d4c593fcec53",
"channel": "6502b140b25bef7561632608",
"author": "64fab77574d7b20fbc7ac3a4",
"createdAt": "2023-09-14T13:20:36.009Z",
"updatedAt": "2023-09-14T13:20:36.009Z",
"__v": 0
},
```
<br>
=> :tada: 이미지 업로드 로직 수정

src/app/(root)/(routes)/(home)/page.tsx, src/app/api/channel/[channelId]/route.ts, src/app/api/posts/route.ts, src/components/templates/CardGridTemplate/CardGridTemplate.tsx, src/components/templates/CardGridTemplate/index.scss, src/config/constants.ts, src/hooks/useInfiniteScroll.ts, src/queries/channel/index.ts, src/services/channel/index.ts
관련 이슈: #15 
-
<br>
- useInfiniteQuery + Intersection Observer 를 사용하여 무한스크롤을 구현했습니다.
- useInfiniteScroll 훅을 만들었습니다.
- useInifiniteQuery가 반환하는 `fetchNextPage`, `hasNextPage`를 인자로 전달하면 IntersectionObserver의 관찰 대상인 ref (`observerElem`)를 반환합니다. 반환해주는 ref를 관찰 대상 Element에 ref 값으로 지정해주시면 됩니다.
<br>
=> 🎉 메인 페이지 무한 스크롤 (훅 분리 완료)

src/app/(root)/layout.tsx, src/components/organisms/Header/index.scss, src/components/organisms/NavBar/index.scss, src/styles/layout.scss
관련 이슈: #104 
<br>
- 사이드바 width는 20rem으로 고정, height는 100%로 설정했습니다.
- 헤더같은 경우 width는 100% - 20rem으로 설정하고, height는 5rem으로 고정했습니다.
- 메인은 헤더와 같은 width에 height는 auto로 설정했으며, padding을 주었습니다.
-
<br>
=> :tada: 메인 레이아웃 수정 완료

package-lock.json, src/components/atoms/DarkModeButton/index.tsx, src/components/organisms/Header/Header.tsx, src/hooks/useStorage.ts
관련 이슈: #110 
Closes #110 
- 새로고침을 해도 로컬 스토리지가 초기화되지 않도록 문제를 수정했습니다.
<br>
- 다크모드 버튼이 [ssr되지 않는 Lazy Loading](https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#with-no-ssr) 되도록 해주었습니다.
- ssr이 되지 않기 때문에 처음부터 클라이언트에서 로컬스토리지 혹은 사용자 시스템에 접근할 수 있도록 수정했습니다.
- 아주 정확한 원인은 모르겠지만, 기존에 서버에서의 darkMode값과 클라이언트에서 darkMode 값이 다른 것이 문제였던 것 같습니다.
- 아래와 같은 경고가 뜨고 있더라고요 (초기에 테스트했을 때는 제 시스템이 light라 서버와 클라이언트 값이 일치해서 저 경고를 못 봤고, 빌드에는 문제가 없어서 인지하지 못하고 넘어간 것 같습니다. 이번에는 시스템 환경을 다크모드로 변경해서 테스트했습니다.)
- 보아하니 서버에서는 로컬스토리지나 사용자 시스템 환경에 접근하지 못하기 때문에 코드 상 디폴트 값인 darkMode = false로 가지고 있고, 클라이언트에서는 darkMode를 저의 시스템 환경을 따라 darkMode = true로 읽기 때문에 생긴 문제 같았습니다.
- 그런데.. 서버에서 읽은 값이 다르더라도 클라이언트에서 스토리지에 있는 값을 잘 읽었다면 그거대로 렌더링을 해주면 될 텐데, 왜 끝에 다시 스토리지 값이 초기화되는지는 아직 잘 모르겠습니다.🥲 이것과는 관련이 없는 걸까요?
- 우선은 ssr이 …
=> ✨ 다크모드 새로고침 로컬스토리지 유지

src/components/molcules/ModalDropdownList/ModalDropdownList.tsx, src/components/organisms/Header/Header.tsx
관련 이슈: #123
<br>
- 로그인을 하기 전이라면 로그인 / 회원가입 버튼이 헤더에 보입니다.
- 로그인을 했다면 메인 페이지로 이동되면서 프로필 이미지와 닉네임이 헤더에 보입니다.
- arrow 버튼을 클릭해 로그아웃을 했다면 어떤 페이지에 있든 로그아웃되면서 알림이 뜨고, 메인 페이지로 이동됩니다.(이때 헤더도 로그인 하기 전으로 바뀜)
- 로그인한 상태가 아니라면 계정 정보 수정, 글 작성 등 일부 페이지에 이동을 못합니다.(arrow 버튼 자체가 보이지 않기 때문, 로그아웃을 했다면 메인 페이지로 강제 이동되면서 헤더에서 arrow 버튼이 사라지기 때문)
- useCurrentUser hook을 사용해서 해결하려고 했는데... 못했습니다. 
- useCurrentUser 코드를 참고해 useEffect를 사용해 pathname이 변할 때를 기준으로 rendering을 설정했습니다.
- 로그인을 할 경우 login -> / 으로 페이지 이동, 로그아웃을 할 경우 새로고침(reload) 으로 인해 반드시 useEffect 안의 코드가 실행됩니다.
- 원래는 쿠키 값을 dep에 넣어 기준값으로 삼으려고 했으나 이럴 경우 useEffect 안에 useCurrentUser 로직이 있어야 했습니다.
- useEffect안에 useCurrentUser를 그대로 넣으면 에러가 났고, 다른 방식으로 하려다보니 callback 오류, header 컴포넌트가 render 되지 않는 등의 오류들로 인해 결국 제 방식대로 코드를 구현하게 되었습니다. 
- 제대로 돌아가지만 코드가 많이 지저분해 추후 리팩토링이 필요해 …
=> :tada: 로그인 여부에 따른 반응적 헤더 구현 및 페이지이동 제한 적용(기능 구현 완료)

src/components/atoms/Avatar/index.tsx, src/components/organisms/Header/Header.tsx, src/components/organisms/Header/index.scss, src/components/organisms/NavBar/index.scss, src/styles/layout.scss
관련 이슈: #159 
-
<br>
- nav, header 간 간격 조정
- 전체 화면의 min-width 설정 (1040px)
- 기타 자잘한 스타일 조정
- body의 스크롤 바 삭제
- 전체 스크롤 바가.. 각 유저 페이지 등에 접속 할 때 스크롤바가 없다가 -> CSR 과정에서 글이 로딩되며 스크롤바가 생기는 과정에서 따닥 하면서 새로 페인트 되는 과정이 보기 안 좋아 일단 삭제했습니다. 의견 있으면 부탁드려요.
- 그래서 infinite scroll에서 마지막에 도달했을 경우 마지막 페이지입니다. 정도가 끝에 표시되면 어떨까 생각했습니다. 요것도 의견 부탁드려요. 
<br>
=> :sparkles: minor layout 조정

src/components/organisms/CardUserItem/CardUserItem.tsx, src/components/organisms/CardUserItem/index.scss, src/components/organisms/CardUserItem/index.stories.ts, src/components/organisms/CardUserItem/index.ts
관련 이슈: #170
<br>
- 검색페이지에서 사용되는 유저 프로필 카드형 컴포넌트를 구현했습니다.
- type 폴더에 있는 user interface를 수정하려고 했으나 이 부분은 민희님께서 맡으신 팔로우 부분과 밀접한 관련이 있어서 결국 수정하지 않았습니다.(자체적 type 만들어 해결함)
<br>
=> :tada: 유저 카드형 프로필 컴포넌트 구현

src/app/(root)/(routes)/(home)/page.tsx, src/components/organisms/CardPostItem/CardPostItem.tsx, src/components/organisms/userPostsGrid/userPostsGrid.tsx, src/utils/htmlTagParser.ts
관련 이슈: #183 
-
<br>
- html tag를 파싱해서 텍스트만 추출하도록 했습니다. (p -> h6 -> ... -> h1 순으로 확인)
- post card 컴포넌트에 적용시켜 두었습니다.
-
<br>
=> :tada: html 태그 파싱

src/app/api/posts/author/route.ts, src/app/api/search/all/[keyword]/route.ts, src/components/organisms/PostGrid/PostGrid.tsx, src/components/organisms/UserDetailCard/UserDetailCard.tsx, src/components/organisms/userPostsGrid/userPostsGrid.tsx
관련 이슈: #186 
-
<br>
- 검색 페이지에서 현재 채널의 ID를 받아서 포스트 들 중 같은 채널의 포스트만 반환하게 수정했어요
- 프로필 페이지에서 유저가 현재 채널에서 작성한 포스트만 나타나게 바뀌었습니다.
-
<br>
=> 🐛 게시글 검색페이지, 유저 프로필 페이지에서 현재 채널의 상태만 반영

src/lib/contexts/authProvider.tsx
관련 이슈: #212 
-
<br>
- 로그인 안된 유저가 내정보 페이지 접근시 로그인 페이지로 이동하게 했습니다.
-
<br>
=> 🎉 로그인 안된 유저가 내정보 페이지 접근시 라우팅

src/app/api/posts/author/route.ts, src/app/api/search/all/[keyword]/route.ts, src/components/organisms/CardPostItem/CardPostItem.tsx, src/components/organisms/CardPostItem/index.scss
관련 이슈: #160 
- CardPostItem 에서 클릭 영역 조정
- 검색 결과 및 유저 프로필에서 쓰이는 CardPostItem의 title 데이터가 파싱되지 않는 문제 해결
<br>
- 게시글 카드 클릭 영역 구분
- 아바타 프로필 이미지에 게시글 이미지 들어가는 문제 해결
<br>
- 기존에 검색 결과 페이지, 유저 프로필 페이지에서 title 데이터가 파싱되지 않아 json 데이터가 그대로 제목에 노출되는 문제 해결
- 검색 결과 반환 및 유저 게시글 불러오는 api에서 title 데이터를 title, description으로 나누도록 수정
- api 보면서 발견한 건데, 사용자 검색이 안 되는 문제가 channel을 필터링하면서 사용자 검색 결과가 같이 필터링이 되더라구요. 발견한 김에 함께 수정해두었습니다! @Lim-JiSeon 
-
<br>
=> Post 카드 레이아웃 조정 및 title 데이터 파싱 처리

src/components/organisms/CardUserItem/CardUserItem.tsx, src/components/organisms/CardUserItem/index.scss, src/components/organisms/Header/index.scss, src/components/organisms/PostGrid/PostGrid.tsx, src/components/organisms/SearchPostItem/SearchPostItem.tsx, src/components/organisms/SearchPostItem/index.scss, src/components/organisms/SearchPostItem/index.ts
관련 이슈: #222 
<br>
- 검색 페이지에서 게시물에서는 작성자 프로필을 삭제했습니다. (api res로 오는 값에 작성자 프로필을 채울 데이터가 없기 때문)
- (결과적으로)전용 검색 페이지 게시물 카드를 만들었습니다.
- 검색 페이지의 유저 프로필 카드에서 유저 닉네임이 길어질 경우 ... 으로 처리했습니다.
- (마찬가지로) 헤더부분에서도 아바타의 길이를 제한하고 ... 처리를 추가했습니다. 
- 새로운 검색 페이지 전용 포스트 카드를 만든 이유는 다음과 같습니다.
- api의 res로 author를 id 값인 string만 넘겨주는데 이럴 경우 author의 fullName, image 를 알 수 없습니다. 
- 이를 해결하기 위해서는 받은 id를 이용해서 User 객체를 받을 수 있는 api를 추가로 호출해야 합니다. 
- 이에 비효율적이라 판단 결국 검색 페이지에서 게시물에 한해서만 제거하게 되었습니다.
- 민희님께서 게시물 상세 페이지에서 작성자 프로필 페이지로 이동할 수 있는 링크를 추가해주면서 필수적으로 추가할 필요성이 낮아졌기 때문도 있습니다. (감사합니다 민희님!!)
<br>
- 검색 페이지에서 보이는 게시물 카드
- 헤더 수정
- 검색 페이지에서 보이는 유저 프로필 카드
=> 🎉 검색 페이지 유저프로필 이동 에러 처리 및 일부 스타일 조정

src/components/molcules/EditNamesForm/EditNamesform.tsx, src/components/molcules/EditProfileImageForm/EditProfileImageForm.tsx, src/components/molcules/EditProfileImageForm/index.scss
관련 이슈: #237 
-
<br>
- 프로필 이미지 파일 선택 input에 톱니바퀴 아이콘을 추가하여 좀 더 파일을 선택하는 input임을 알기 쉽게 수정 되었습니다.
- 프로필 이미지를 선택하지 않고 프로필 이미지 변경 버튼 클릭 시 파일을 선택해달라고 알림이 뜨게 수정 되었습니다.
- 닉네임 변경 버튼의 크기와 위치가 닉네임만 변경 한다는 것을 알 수 있게 수정 되었습니다.
- 
<br>
=> 🎉 계정 정보 변경 페이지 ui 변경

src/hooks/useFollow.ts
관련 이슈: #246 
- 팔로우 신청을 먼저하는 것부터 연달아 토글을 할 때는 문제가 없었는데, 삭제부터 할 때는 그 다음 삭제가 에러가 났던 문제
<br>
원인
: 삭제할 때 id를 currentUser에서 해당 팔로우 정보를 불러와서 찾은 id를 넘기는데, 신청할 때 currentUser의 팔로우 정보를 업데이트시켜주지 않아 이전 id값으로 delete요청을 보내고 있었습니다.. 이전에 재희님이 작성하신 코드를 제가 잘못 건드려서 발생했던 문제네요 😂
팔로우 신청을 하면 currentUser의 팔로우 정보를 업데이트 시켜주어 해결했습니다!
-
<br>
=> 🐛 팔로우 삭제 -> 신청 -> 삭제 에러 해결

src/components/atoms/Loading/Loading.tsx, src/components/atoms/Loading/index.scss, src/components/atoms/Loading/index.stories.ts, src/components/atoms/Loading/index.ts, src/components/molcules/FollowListItem/FollowListItem.tsx, src/components/molcules/FollowListItem/index.scss, src/components/organisms/UserDetailCard/section/Follows.tsx, src/queries/comments/index.ts
관련 이슈: #231 
-
<br>
- 모달 열었을 때, 닫았을 때 transition 효과를 주려면 초기 로딩 시 아예 렌더링이 되지 않게 막을 수는 없는 것 같습니다 (저의 지식과 능력의 범위 안에서는요.. 방법을 아시는 분 계시면 알려주세요..!)
- 그래서 차선책으로 모달 껍데기는 렌더링이 되게 하고, 그 안의 내용 (팔로우 리스트)은 모달을 열었을 때 조건부 렌더링되도록 처리했습니다.
- 따라서 유저 프로필 페이지로 이동하자마자 팔로우 정보를 위해 api 다다다 호출하는 건 이제 모달을 열었을 때 요청이 갑니다.
<br>
- 추가로 구조 상 팔로우 리스트는 api요청이 많기 때문에 렌더링 되기까지 로딩 컴포넌트가 뜨도록 Suspense와 LazyLoading을 사용했습니다.
- query key 추가한 커밋은 작업하면서 경고?에러?가 뜨길래 추가해놨던 건데, 효중님 @khj0426 이 수정해주신 PR 확인했습니다! 충돌나면 제가 작성한 걸 지우면 될 것 같습니다.
- 추가로 팔로우 리스트에서 닉네임이 긴 아바타가 가로로 넘치는 문제를 수정했습니다.
<br>
=> 🎉  팔로우 리스트 모달 api 호출 지연, 로딩 컴포넌트 추가

src/app/(root)/(routes)/(home)/page.tsx, src/app/api/posts/author/route.ts, src/app/api/posts/route.ts, src/components/templates/CardGridTemplate/CardGridTemplate.tsx, src/queries/channel/index.ts
관련 이슈: #219 
- 괜히 이상하게 코드를 짜서 혼란이 있었네요.. 먼저 사죄의 말씀..올림니다..
- 기존 코드 갈아엎고 특정 채널의 포스트 목록을 가져오는 api로 변경했습니다
<br>
- 좋아요,싫어요 변경 시 홈으로 가면 바로 해당 좋아요 싫어요가 반영이 됩니다 !
- 글을 작성하면 바로 홈에 반영이 되게 수정했습니다.
- 추가적으로 회원 정보 변경 시 홈으로 리다이렉트 -> 바로 바뀐 내용이 적용되도록 queryKey에 현재 유저를 추가했습니다
- 만약 해당 경우에도 바로 반영이 안되면 멘션 달아주세요!!
<br>
=> 🐛 글 작성 시 바로 홈 화면에 반영되게 설정

src/components/molcules/EditNamesForm/EditNamesform.tsx, src/components/molcules/EditProfileImageForm/EditProfileImageForm.tsx, src/hooks/useCurrentUser.ts
관련 이슈: #236 
-
<br>
- 계정 정보 변경 페이지에서 닉네임, 프로필 이미지를 변경했을 때 계정 정보 변경 페이지, 헤더, 사이드바에 적용되지 않던 현상을 바로 적용되게 수정 하였습니다.
- 
<br>
=> 🐛 닉네임, 프로필 이미지 변경시 바로 적용

src/components/organisms/Header/Header.tsx, src/hooks/useDarkmodeCookie.ts
관련 이슈: #256
<br>
- 서버에서 쿠키를 저장하는 부분을 제거했습니다.
- 서버에서 쿠키를 저장하려면 api router를 만들거나 13.4버전부터 실험적으로 도입된 Server Action이라는 걸 써야하는데, 그럴 필요 없이 그냥 쿠키에 저장하는 건 클라이언트 컴포넌트인 다크모드 버튼 컴포넌트 안에서 처리하기 때문에 그냥 삭제했습니다.
- 쿠키에 저장된 값을 가져오는 로직을 훅으로 분리해서 Header의 코드를 줄였습니다.
-
<br>
=> :bug: 서버 쿠키 set 제거 (다크모드 client component에서 처리)

src/app/(root)/layout.tsx, src/app/api/login/route.ts, src/components/molcules/AvatarDropdown/AvatarDropdown.tsx, src/components/organisms/Header/Header.tsx, src/components/templates/HomePageTemplate/index.tsx, src/config/environments.ts, src/hooks/useLogin.ts, src/hooks/useSignup.ts, src/lib/contexts/authProvider.tsx
관련 이슈: #258
-
<br>
- header에서 유저 프로필을 로드하는 방식을 SSR로 전환
- 로그인, 로그아웃, 회원가입에 대해 리로드하는 방식으로 `location.reload()` 처리로 통일
- `location.reload()`로 하는 것에 대한 거부감이 있었는데, 생각해보니 매번 로그인, 로그아웃이 되는 것도 아니고 적합한 동작이 아닌가 싶어 전환했는데 의견 부탁드립니다.
<br>
=> :sparkles: header 로딩 방식 수정

src/app/(root)/(routes)/(home)/page.tsx, src/app/api/follow/create/route.ts, src/components/atoms/CirclePlusButton/CirclePlusButton.tsx, src/components/atoms/ImageButton/imageButton.tsx, src/components/organisms/CardPostItem/CardPostItem.tsx, src/components/organisms/LogInForm/LoginForm.tsx, src/components/organisms/NavBar/NavBar.tsx, src/components/organisms/NavBar/UserList/HydratedUserList.tsx, src/components/organisms/NavBar/UserList/UserList.tsx, src/components/templates/CardGridTemplate/GridController.tsx, src/components/templates/CardGridTemplate/HydrateCardGrid.tsx, src/lib/queryClient.ts, src/queries/channel/index.ts, src/queries/users/index.ts, src/utils/htmlTagParser.ts
관련 이슈: #260
-
<br>
- 유저 목록에 대한 사전 dehydrate state 전달
- 유저 목록 옆 팔로우 버튼 삭제
- 홈 페이지 포스트에 대한 prefetch
- c2c0e0a7e371bdb3a3c99565039cf12829090660 커밋에 대해 의견 남겨주세요
- SSR로 state를 전달하면 상세 유저 페이지에서 팔로우, 팔로우의 여부가 즉시 사이드바와 동기화되지 않습니다... 라 작성하던 중에 보니까 애초에 CSR 배포 버전에서도 안 되네요.
- 그리고 인스타 등을 봤더니 같은 대상에 대한 팔로우 버튼이 한 화면에 있는 경우가 없더군요... (역시 이유가 있는 디자인...)
- 즉, 화면에 같은 대상에 대한 팔로우 버튼을 동기화 하는데 사용되는 비용과 비교한 trade off라고 생각합니다.
<br>
=> :sparkles: 유저 목록 및 포스트 로딩 방식 수정

src/app/(root)/(routes)/post/[postId]/page.tsx, src/components/molcules/LikeDislikeCount/LikeDislikeCount.tsx, src/components/molcules/LikeDislikeCount/index.stories.ts, src/components/organisms/CardPostItem/CardPostItem.tsx, src/components/organisms/LikeDIsLikeProgressBar/index.stories.tsx, src/components/organisms/LikeDIsLikeProgressBar/index.tsx, src/components/organisms/LikeDisLikeContainer/LikeDIsLikeContainer.tsx, src/components/organisms/LikeDisLikeContainer/index.scss, src/components/organisms/LikeDisLikeContainer/index.stories.tsx, src/components/organisms/SearchPostItem/SearchPostItem.tsx, src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx, src/hooks/useDisLike.ts, src/hooks/useLike.ts, src/hooks/useLikeState.ts
관련 이슈: #267 
-
<br>
- 좋아요 싫어요를 취소할 수 있습니다(유저가 좋아요 누른 상태->다시 누르면 취소)
- 누른 상태에 대해 이미지를 추가했습니다(이전에 좋아요를 눌렀으면 좋아요따봉의 활성화이미지)
- template에서 로직이 너무 많아 훅으로 분리했습니다.
-
<br>
=> ✨ 좋아요 싫어요 상태별 이미지 추가, 취소 가능하게 설정

src/components/molcules/ModalLayout/index.scss, src/components/organisms/FollowList/FollowList.tsx, src/components/organisms/FollowList/index.scss, src/components/organisms/UserDetailCard/section/Follows.tsx, src/hooks/useFollow.ts, src/hooks/useModal.ts
관련 이슈: #271 
- [a044552](https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/pull/281/commits/a044552fee509a5c1cb6ffb5187a9c7febfa45a7), [70dc701](https://github.com/prgrms-fe-devcourse/FEDC4_Price-PCC_DONGYOUNG/pull/281/commits/70dc701457f3accd5c9c6c60bb2b6259bbf36ca3)  두 개만 보시면 됩니다
<br>
- 기존에 유저 프로필 페이지에서 스크롤을 아래로 어느정도 한 상태에서 모달을 켜면 그만큼 위에 뜨는 문제를 수정했습니다.
- 모달을 켠 상태에서는 body 스크롤이 안되도록 useModal 훅 내에 overflow hidden처리 해두었습니다.
-
<br>
=> :bug: 모달 스크롤 방지

src/components/molcules/ModalLayout/index.scss, src/components/organisms/FollowList/FollowList.tsx, src/components/organisms/FollowList/index.scss, src/components/organisms/NavBar/UserList/UserList.tsx, src/components/organisms/UserDetailCard/section/Follows.tsx, src/hooks/useFollow.ts, src/hooks/useModal.ts, src/queries/users/index.ts, src/types/user/index.ts
관련 이슈: #272 #243 
-
<br>
- 유저 디테일 카드에서 팔로우 / 팔로우 취소 시 모달에도 낙관적 업데이트
- updatedUserData 복사본을 만들어 모달의 FollowList에 전달
- User 제네릭 타입을 제거하고 User 또는 UserSummary를 사용하도록 수정
<br>
=> :bug: 팔로우 모달 낙관적 업데이트

package-lock.json, src/app/(root)/(routes)/user/edit/profile/page.tsx, src/components/molcules/EditNamesForm/EditNamesform.tsx, src/components/molcules/EditProfileImageForm/EditProfileImageForm.tsx, src/components/organisms/EditProfile/EditProfile.tsx, src/components/organisms/Header/Header.tsx, src/components/organisms/PasswordInputModal/PasswordInputModal.tsx
관련 이슈: #262, #273 
-
<br>
- 비밀번호 검증 모달 닫기 버튼을 누르면 바로 홈으로 이동하게 수정했습니다.
- 계정 정보 수정을 하면 location.reload() 하도록 변경했습니다.
- 계정 정보 수정 페이지에서 reload를 할 시 비밀번호 검증 모달창이 다시 뜨는 현상이 있어 비밀번호 검증 여부를 쿠키에 저장하도록 추가하였습니다.
- 비밀번호 검증 여부를 쿠키에 저장하는 방식은 악의적으로 쿠키를 임의로 생성할 가능성도 배제할 순 없어 다른 방법이 없을지 고민중이지만 우선 쿠키에 저장하도록 했습니다.
<br>
=> 🐛 비밀번호 검증 모달, 계정 정보 수정 페이지 버그 수정

src/components/molcules/ModalDropdownList/ModalDropdownList.tsx, src/components/molcules/PostOptionsDropdown/PostOptionsDropdown.tsx, src/components/organisms/CardPostItem/CardPostItem.tsx, src/components/organisms/CardUserItem/CardUserItem.tsx, src/components/organisms/NavBar/UserList/UserList.tsx, src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
관련 이슈: #
- Link에 대한 prefetch 재활성화
<br>
- 기존 과도한 요청으로 인해 지운 Link 컴포넌트의 prefetch를 활성화했습니다.
**공통 사항이니 의견 부탁드립니다**
- 기존에는 CSR 처리되는 요청에 prefetch 요청이 중복되어 안 좋은 성능을 보였었는데, 이제 서버에서 렌더링되거나 tanstack query prefetch 되어 오는 화면이 있기 때문에
- 다른 페이지로 전환 시 더 빠른 속도를 위해 (좀 느리다고 느꼈습니다) `prefetch={false}` 옵션을 삭제했습니다.
- 현재 배포 링크(현재 테스트로 계속 사용 중인 배포 링크)에서 일단 적용시켜 보았으니 배포 환경에서의 확인이 가능합니다.
<br>
=> :sparkles: Link Prefetch 적용

src/components/molcules/FollowListItem/FollowListItem.tsx, src/components/organisms/FollowList/FollowList.tsx
관련 이슈: #
-
<br>
- 팔로우 사용자 아이템 데이터를 불러오는 동안 로딩처리되도록 useQuery의 isLoading을 사용했습니다.
-
<br>
=> :refactor: suspense -> useQuery isLoading으로 변경

src/hooks/useFollow.ts
관련 이슈: #312 
-
<br>
- 유저 프로필에서 팔로우를 했을 때 팔로워 모달을 열면 바로 내가 바로 반영되도록 updatedUser 상태를 새로 만들었었음
- 데이터를 다 불러와서 userData가 undefined가 아니게 되면 updatedUser도 같이 업데이트를 해줬어야 함
- 그걸 안하면 updatedUser도 계속 undefined라 undefined 방어 코드 (조건문)에서 리턴돼서 팔로우가 제대로 동작을 못하고 있었음
<br>  
- userData가 불러와지면 updatedUserData도 같이 업데이트하도록 수정했습니다 !!!
-
<br>
=> :bug: 모달에서 팔로우/팔로우 취소 동작 안되는 문제 해결

README.md
=> :memo: readme 업데이트
