src/app/(root)/layout.tsx
src/components/atoms/DarkModeButton/index.tsx
src/hooks/useStorage.ts

관련 이슈: #38 
-
<br>
- 서버에서 window를 읽게 될 때 undefined인 경우에 대한 방어코드를 추가했습니다.
- 추가로 global-layout.scss를 중복으로 import하는 문제를 수정했습니다. (알려주신 효중님 감사합니다... 앞으론 꼭 build해보고 올리기🫠)
-참고 링크:
https://www.slingacademy.com/article/solving-the-window-is-not-defined-error-in-next-js/
<br>

🐛 window undefined 오류 수정

---

src/components/molcules/file-picker/index.tsx

관련 이슈: #27 
-
<br>
- 상단에 'use client'구문을 깜빡해서 추가했습니다.!.!
-
<br>

🐛 use client 구문 추가

---

src/components/molcules/file-picker/index.tsx

관련 이슈: #2 
-
<br>
- 기본적인 높이, 너비를 피그마대로 똑같이 수정했습니다..!!
-
<br>

✨  파일 업로드 컴포넌트의 기본 높이, 너비 수정

---

next.config.js
src/app/(root)/layout.tsx

:bug: global-style import 수정

---

src/hooks/useCurrentUser.ts
src/lib/contexts/authProvider.tsx

:sparkles: APP_PATH import 수정

---

.storybook/main.ts
next.config.js

관련 이슈: #63 
<br>
- storybook 포함 scss에서의 alias 설정
사용 예시 
```scss
@import '@/styles/variables';
.input {
width: 100%;
height: 100%;
&.default {
border: none;
}
}
```
<br>

:tada: scss에서 alias 설정

---

src/components/atoms/ImageButton/imageButton.tsx
src/components/atoms/ImageButton/index.stories.ts

관련 이슈: #24 
<br>
- 알림 버튼이 아닌 이미지 버튼으로 컴포넌트 방향성 전환
-  이미지 클릭시 props로 전달받은 이벤트 실행
- props로는 src, onClick은 필수로, shape, alt, size는 선택
- shape : circle(default), rounded, square
- alt : image-button(default)
- size: 50(default)
<br>
```javascript
<ImageButton 
shape="rounded"
alt="이미지 버튼"
src="https://picsum.photos/200/200"
size=100
onClick={handleImageButton}
/>
```
```javascript
<ImageButton 
src="https://picsum.photos/200/200"
onClick={handleImageButton}
/>
```
<br>
현재 사진에 있는 이미지는 rem으로 수정하기 전 사진으로 rem으로 수정후에는 size를 5로 주면 같은 결과값이 나옵니다.

🎉 이미지 버튼 컴포넌트 구현(최종)

---

src/components/molcules/file-picker/index.stories.tsx
src/components/molcules/file-picker/index.tsx
src/utils/FiletoBaseUrl.ts

관련 이슈: #27 
-
<br>
- File을 base64로 변경
-
<br>

🎉 이미지 업로드 컴포넌트 File -> base64로 변경

---

package-lock.json
src/app/(root)/layout.tsx
src/components/organisms/Header/Header.tsx
src/styles/color-themes.scss
src/styles/global-layout.scss
src/styles/layout.scss

관련 이슈: #74 
-
<br>
- 공용 레이아웃 구현 
- 헤더와 사이드바는 샘플입니다. 
- 헤더와 사이드바는 fixed 되어 있습니다.
- 헤더와 사이드바는 z-index가 main보다 높게 설정되어 있어 main의 width나 height가 길어질 경우 헤더와 사이드바에 가려집니다. 
예시 사진(이 사진은 배경색 문제 해결 전 찍은거라 배경색이 적용되지 않았습니다.)
<br>
- 혹시 main에 컴포넌트들을 배치할 때 문제가 된다면 연락해주세요.
- 현재 main은 display가 flex이며, flex-direction은 column 입니다.

🎉  공용 레이아웃 구현 완료

---

src/components/molcules/LikeDislikeCount/index.scss
src/components/organisms/CardPostItem/index.scss
src/config/environments.ts

관련 이슈: #94 
-
<br>
- 위치를 수정했습니다.
- Environment에서 assertEnv 사용 안함 (도커 빌드 문제)
-
<br>

:sparkles: 따봉 위치 position absolute + assertEnv 사용 안함

---

src/app/api/auth-user/route.ts
src/app/api/login/route.ts
src/app/api/logout/route.ts
src/app/api/posts/create/route.ts
src/app/api/signup/route.ts
src/app/api/users/route.ts
src/lib/axios.ts
src/lib/axiosSever.ts

관련 이슈: #108 
<br>
- axios client와 server용 분리
- baseUrl 분리 적용
- 기존 api에 대한 테스트 완료
- 요 변경사항 적용된 버전으로 작업해주시면 될 것 같습니다!
<br>

:bug: axios url 수정

---

src/components/atoms/Input/index.scss
src/components/atoms/Quill/Quill.tsx
src/components/atoms/Quill/index.scss
src/hooks/useUploadForm.ts
src/lib/contexts/authProvider.tsx

관련 이슈: #112
-
<br>
- 업로드 페이지 다크모드 최적화
- 업로드 페이지 업로드 후 리다이렉팅
- auth 권한에 따른 접근 권한 설정
-
<br>

🎉 1차 스프린트 변경사항 적용

---

src/app/api/login/route.ts
src/app/api/logout/route.ts
src/app/api/posts/create/route.ts
src/components/molcules/ModalDropdownList/ModalDropdownList.tsx
src/components/organisms/LogInForm/LoginForm.tsx
src/hooks/useCurrentUser.ts
src/hooks/useLogin.ts
src/hooks/useLogout.ts
src/hooks/useServerCookie.ts
src/hooks/useSignup.ts
src/lib/contexts/authProvider.tsx

관련 이슈: #129
-
<br>
- auth provider 의존성 추가
- token 저장 방식 변경
- 기타 로그인, 로그아웃 방식 통일 등
- 최적화가 조금 필요할 것 같은데... 일단 버그 없는지 확인 후 추후에 하겠습니다.
<br>

:bug: auth validation 수정

---

next.config.js
package-lock.json
package.json
src/components/molcules/file-picker/index.scss
src/components/molcules/file-picker/index.tsx
src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
src/components/templates/PostDetailTemplate/index.scss

관련 이슈: #111 
-
<br>
- 파일 업로드 컴포넌트 e.preventDefault 설정
- 파일 업로드 이미지 클릭 범위 조정
- postDetail페이지에서 받은 post 파싱해서 랜더링
<br>

🎉 이미지 컴포넌트 리팩토링 + 포스트 디테일 페이지 레이아웃 수정..!

---

src/app/(root)/(routes)/user/[userId]/page.tsx
src/components/atoms/Card/Card.tsx
src/components/organisms/UserDetailCard/UserDetailCard.tsx
src/components/organisms/UserDetailCard/index.scss
src/components/organisms/UserDetailCard/index.tsx
src/components/templates/UserDetailPageTemplate/UserDetailPageTemplate.tsx
src/components/templates/UserDetailPageTemplate/index.scss
src/components/templates/UserDetailPageTemplate/index.tsx

관련 이슈: #134
-
<br>
- 유저 상세 페이지 레이아웃 설정
- 
<br>

:tada: 유저 상세 페이지 레이아웃

---

package-lock.json
src/components/organisms/NavBar/index.scss

관련 이슈: #141 
<br>
- 사이드바 스크롤 디자인 간단하게 수정했습니다.
- 평소에는 보이지 않고, hover 시에만 스크롤이 보입니다.
- 색상은 gray-4로 했습니다.
- 추후 시간이 된다면 그래서 디자인이 별개로 나온다면 수정해도 괜찮을 것 같습니다.(과연 그렇게 될지는.... ^^;;)
<br>
라이트 모드일 때
다크 모드일 때
마우스 커서를 올리지 않았을 때

🎉 사이드바 스크롤 디자인 수정

---

pnpm-lock.yaml
src/app/(root)/layout.tsx
src/app/api/signup/route.ts
src/components/atoms/Toast/ToastContainer.tsx
src/components/organisms/SignUpForm/SignUpForm.tsx
src/hooks/useCurrentUser.ts
src/hooks/useLogin.ts
src/hooks/useLogout.ts
src/hooks/useSignup.ts

관련 이슈: #162
<br>
- auth logic 원복
- toast client 처리
- 비슷한 주제로 자주 bug fix 해서 죄송합니다..
<br>

:bug: auth와 hydrate에러 수정

---

src/components/molcules/file-picker/index.tsx

관련 이슈: #2 
-
<br>
- 버튼 타입을 기본 submit->button으로 바뀌었습니다. 이제 잘 동작합니다!
-
<br>

🎉 이미지 업로드 버튼 타입 submit에서 button으로 수정

---

src/components/atoms/Card/Card.tsx

관련 이슈: #
-
<br>
- 카드 컴포넌트 claassNames추가
-
<br>

🎉 카드컴포넌트 import 수정

---

src/components/organisms/NotificationModal/NotificationModal.tsx
src/components/organisms/NotificationModal/index.scss
src/components/organisms/NotificationModal/index.stories.tsx
src/components/organisms/NotificationModal/index.ts
src/constants/notification.ts
src/types/notification/index.ts

관련 이슈: #120 
<br>
- 알림 모달 창 컴포넌트 구현했습니다.
- 알림 타입 수정했습니다. 
- 추후 api 연결과 관련된 새로운 알림 타입들은 새로 interface를 만들어 관리할 예정입니다. (예 : NotificationSummary)
- 댓글 타입을 추가했습니다.
- 모두 읽음에 별도 이벤트가 없는 것 같아서 hover를 임의로 넣었습니다.(글자색이 primary-1로 변함)
- 알림 폰트가 없어서 임의로 body1로 했습니다.
<br>

🎉  알림 모달창 구현

---

package-lock.json
src/app/(root)/(routes)/user/edit/profile/page.tsx
src/components/organisms/PasswordInputModal/PasswordInputModal.tsx
src/components/organisms/PasswordInputModal/index.ts
src/hooks/useCheckPassword.ts

관련 이슈: #117 
-
<br>
- 내 정보 페이지에 접근하기 위한 비밀번호 검증 모달을 구현했습니다.
- 뭔가 돌아가는 쓰레기를 만든 기분이라 리팩토링을 할 부분이 많을 것같습니다...
<br>

🎉 비밀번호 검증 모달 구현

---

src/app/api/follow/create/route.ts

관련 이슈: #
-
<br>
- follow 시 notification 요청을 함께 전송합니다.
-
<br>

:tada: follow 요청 시 notification 전송

---

package-lock.json
src/components/atoms/FollowToggleButton/FollowToggleButton.tsx

관련 이슈: #192 
<br>
- 토글 버튼 클릭 이벤트 시 처리하는 함수를 만들어 followToggle은 비동기 await 처리하고, 이 함수가 처리되는 동안은 버튼을 비 활성화시킨 뒤 처리가 끝나면 다시 활성화되도록 설정했습니다.
- 여러번 클릭해도 이제는 먼저 호출된 followToggle이 처리될 때까지 버튼이 비활성화됩니다.
<br>

🎉 팔로우 버튼 다중클릭시 발생하는 네트워크 오류 해결

---

src/app/api/posts/author/route.ts
src/app/api/search/all/[keyword]/route.ts
src/components/organisms/CardPostItem/CardPostItem.tsx
src/components/organisms/CardPostItem/index.scss
src/components/organisms/NavBar/NavBar.tsx
src/components/organisms/NavBar/index.scss
src/queries/users/index.ts

관련 이슈: #216 
<br>
- usequery 부분에서 query key를 수정했습니다. 
- 회원가입 후 데이터를 다시 서버에서 불러옵니다.
- 이전까지는 query키가 동일했기 때문에 데이터를 호출하더라도 기존에 저장되어 있던 데이터를 불러왔기 때문에 적용이 즉각적으로 이루어지지 않았습니다.(새로고침하거나 페이지 이동 시 적용되는 건 staleTime이 0으로 기본설정되었기 때문에 refetch로 인한 것으로 추정)
- 수정하면서 query key를 다르게 주어 회원가입 또는 다른 아이디로 로그인 시 데이터를 서버로부터 다시 불러오도록 설정했습니다.(처음 로그인 또는 회원가입 시에만 서버로부터 데이터를 불러오고 그 이후는 한 번 불러온 데이터를 가져다 씁니다. 다만 staleTime이 0이기 때문에 refetch는 이루어집니다.)
- 저도 완벽하게 이해한 것은 아니지만 제가 이해한 것은 위에 정리한 내용과 같습니다.
**커밋 94a23d25c688b1e6cbc3553dba398f852a17bb0f 만 보시면 됩니다.**
<br>

🎉  회원가입 후 사이드바 데이터 바로 적용

---

src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx

관련 이슈: #
-
<br>
- 댓글 알림 api에 userId부분에 글 작성자의 id를 넣게 수정했어요
-
<br>

🎉 댓글 api 알림 부분 수정

---

.github/workflows/pull-request.yml

관련 이슈: # 
- 빌드 시 싫어요 채널의 ID가 없어서 빌드 실패가 발생합니다.!
<br>
- github secrets에 싫어요 채널 환경변수를 추가했고 코드에도 반영했어요!
-
<br>

🎉 싫어요 채널 환경변수 추가

---

src/components/molcules/ModalLayout/index.scss

관련 이슈: #235 
-
<br>
- 모달 위치가 viewport 가운데 오도록 수정했습니다.
- viewport가 줄어들면 모달창이 사이드바와 헤더에 가려지는 것이 어색한것 같아 모달의 z-index를 증가시켰습니다.
- 모달이 전체화면을 덮는 것이 ux적으로 불편한점도 약간은 있을 수 있어서 코멘트정도 부탁드립니다
- 예를들어 사이드바와 헤더를 클릭하기 위해서는 모달창을 끄고 누를 수 있다
<br>

🐛 모달 레이아웃 수정

---

src/app/api/create-comment/notification/route.ts
src/app/api/notifications/seen/route.ts
src/app/api/users/edit/password/route.ts
src/components/atoms/NotificationButton/NotificationButton.tsx
src/components/organisms/NotificationModal/NotiList.tsx
src/components/organisms/NotificationModal/NotificationModal.tsx
src/services/notification/index.ts

관련 이슈: #224 
-
<br>
- 알림 기능의 여러 문제를 개선했습니다.
오류 원인에 대해 공유드립니다. @Lim-JiSeon 
- route에서 put 메서드에 대한 config를 body에 넣어 전송하는 코드로 작성되어 있었음
- data.data.length로 알림 여부를 판단하는 코드로 작성되어 있었음 (seen 여부 체크가 필요)
- handleclick에 대한 메서드가 잘못 지정됨
<br>

:tada: 알림 컴포넌트 문제 개선

---

package.json
pnpm-lock.yaml
src/components/templates/ModifyPostPageTemplate/ModifyPostPageTemplate.tsx
src/components/templates/ModifyPostPageTemplate/index.scss
src/components/templates/NewPostPageTemplate/NewPostPageTemplate.tsx
src/components/templates/NewPostPageTemplate/index.scss
src/config/postValidation.ts
src/hooks/useModifyPostForm.ts
src/hooks/useUploadForm.ts
src/services/post/index.ts

관련 이슈: #225 #226
<br>
- 게시글 업로드 및 수정에서 중복 등록 방지
- 게시글 업로드 및 수정에 대한 validation 설정 - zod 도입
-
<br>

:sparkles: 업로드 관련 이슈 수정 및 리팩토링

---

next.config.js

관련 이슈: #227
-
<br>
- 동적 url 지정
-
<br>

:tada: wildcard url 처리

---

src/components/organisms/CommentInput/CommentInput.tsx
src/queries/comments/index.ts

관련 이슈: #249 
- 기존 문제의 댓글 입력 , 삭제시 바로 적용되지 않는 문제를 수정했습니다.!
<br>
- 댓글 목록 불러오는 query부분에서 key 설정
- 
<br>

✨ 댓글 입력시 바로 반영되게 설정

---

src/components/organisms/NavBar/NavBar.tsx
src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx

관련 이슈: #240 
-
<br>
- 사이드바, 게시글 상세 페이지에서 아바타에 Link를 걸었습니다! (hover하면 커서가 pointer로 변합니다.)
-
<br>

🎉 아바타 링크 처리

---

src/app/(root)/layout.tsx
src/components/atoms/DarkModeButton/index.stories.ts
src/components/atoms/DarkModeButton/index.tsx
src/components/molcules/AvatarDropdown/AvatarDropdown.tsx
src/components/molcules/AvatarDropdown/index.scss
src/components/molcules/AvatarDropdown/index.ts
src/components/organisms/Header/Header.tsx
src/components/organisms/Header/index.scss

관련 이슈: #110 
-
<br>
- 서버에서 쿠키를 사용해 다크모드를 저장하도록 했습니다.
- 토글 버튼을 누르면 클라이언트에서 쿠키 갱신,
- 처음 렌더링 시에는 서버에서 쿠키 값 가져옴
- 헤더를 서버 컴포넌트로 두기 위해 아바타 드롭다운 부분만 클라이언트 컴포넌트로 따로 분리했습니다.
-
<br>

:bug: 다크모드 로컬스토리지 -> 쿠키로 수정

---

src/components/organisms/LikeDIsLikeProgressBar/index.tsx
src/components/organisms/LikeDisLikeContainer/index.scss

관련 이슈: #
- 화면크기가 줄여졌을떄 좋아요 싫어요 글자 짤리는 현상
<br>
- 그래프 너비를 vw기준으로 새로 수정했습니다!
-
<br>

✨ 좋아요 싫어요 그래프  너비 수정

---

src/components/molcules/PostOptionsDropdown/PostOptionsDropdown.tsx
src/components/organisms/CardPostItem/CardPostItem.tsx
src/components/organisms/CardPostItem/index.scss
src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
src/config/paths.ts

관련 이슈: #268 
-
<br>
- 드롭다운이 보이지 않는 문제 수정
- 게시글 수정 페이지 링크 연동
- 게시글 상세페이지에서 옵션버튼 크기 조정 (좀 더 크게..)
-
<br>

✨ 드롭다운 스타일 수정, 게시글 수정 페이지 링크 연동

---

package-lock.json
src/components/molcules/AvatarDropdown/index.scss
src/components/organisms/NotificationModal/NotificationModal.tsx
src/components/organisms/NotificationModal/index.scss

관련 이슈: #263 
<br>
- 알림 창 레이아웃을 수정했습니다. 
- 알림이 많아질 경우 스크롤할 수 있게 했으며, 디자인은 사이드바와 같습니다.
- 헤더 스타일 수정한 부분이 merge 과정에서 없어진 것 같아 다시 수정했습니다. (긴 닉네임 ... 처리 등)
-
<br>

🎉 알림 창 scss 수정

---

package-lock.json
src/components/molcules/AvatarDropdown/AvatarDropdown.tsx
src/components/organisms/Header/index.scss
src/components/organisms/NavBar/index.scss
src/components/organisms/NotificationModal/NotiList.tsx
src/components/organisms/NotificationModal/index.scss
src/components/templates/SearchPageTemplate/index.scss

관련 이슈: #266 
<br>
- 검색 결과 페이지에서 카테고리 밀림 레이아웃 수정(사이즈가 많이 줄어들었을 때)
- 사이드바 유저 hover 효과 배경색 넣기(배경색이 어색해 대신 opacity를 0.66 줌)
- 헤더 드롭다운 페이지 이동시 닫힘 효과 넣기(페이지 이동시 자동 닫힘)
- 사이드바 여백 주기(margin)
- 알림에 Link 효과 넣기(댓글 - post 게시물 세부 페이지, 팔로우 - author 프로필 페이지)
-
<br>

🎉 피드백받은 간단한 에러 사항들 수정 - scss

---

src/components/organisms/FollowList/FollowList.tsx
src/components/organisms/FollowList/index.scss
src/components/organisms/UserDetailCard/section/Follows.tsx
src/hooks/useFollow.ts

관련 이슈: #269 #270 
-
<br>
- 비회원인 경우에도 팔로우/팔로잉 숫자를 계산하도록 수정했습니다. (useFollow에서 currentUser 분기처리 이동)
- 팔로우/팔로잉 숫자가 0일 때도 모달이 열리도록 수정했습니다. 
-
<br>

:bug: 비회원의 경우에 팔로우/팔로잉 숫자 0인 문제 + 팔로우 0일 때도 모달 켜지도록 수정

---

src/components/organisms/UserDetailCard/index.scss
src/components/organisms/UserDetailCard/section/Follows.tsx

관련 이슈: #278 
-
<br>
- 모달 버튼 디자인
-
<br>

:sparkles: 팔로우 리스트 모달 버튼 디자인

---

src/components/organisms/CommentInput/CommentInput.tsx
src/components/organisms/CommentList/CommentListContainer.tsx

관련 이슈: #285 
-
<br>
- 댓글 추가 제거 시 알림 처리
-
<br>

🎉 댓글 작성,제거시 알림처리

---

src/components/atoms/NotificationButton/NotificationButton.tsx
src/components/atoms/NotificationButton/index.scss
src/components/atoms/Quill/Quill.tsx
src/components/molcules/AvatarDropdown/AvatarDropdown.tsx
src/components/molcules/ModalDropdownList/ModalDropdownList.tsx
src/components/organisms/NotificationModal/NotiList.tsx
src/components/organisms/NotificationModal/NotificationModal.tsx
src/components/organisms/NotificationModal/index.scss
src/components/templates/PostDetailTemplate/PostDetailTemplate.tsx
src/hooks/useDisLike.ts
src/hooks/useLike.ts
src/lib/axios.ts

관련 이슈: #293
-
<br>
- 모달 및 드랍다운 레이아웃 재조정
- 외부 클릭 시 자동으로 닫히는 기능 추가
-
<br>

:sparkles: 드랍다운 및 모달 추가 처리

---

public/images/optionsIconWhite.svg
src/components/atoms/DarkModeButton/index.tsx
src/components/molcules/PostOptionsDropdown/PostOptionsDropdown.tsx
src/config/assets.ts
src/hooks/useDarkMode.ts

관련 이슈: #
-
<br>
- 글 상세 페이지에서 ... 다크모드 시 다른 이미지 처리
-
<br>

🎉 다크모드 ...이미지

---

src/components/organisms/NavBar/UserList/UserList.tsx
src/components/organisms/NotificationModal/NotiList.tsx
src/components/organisms/NotificationModal/index.scss
src/components/templates/PostDetailTemplate/index.scss

관련 이슈: #302 
<br>
- 알림 데이터 필터링했습니다.(follow가 null일 경우, comment가 null일 경우, author가 현재 유저일 경우)
- 상세 페이지에서 닉네임이 너무 길어질 경우 ... 처리했습니다.
-
<br>

🎉 error  bug

---

src/components/organisms/NavBar/UserList/UserList.tsx
src/components/organisms/NotificationModal/NotiList.tsx
src/components/organisms/NotificationModal/index.scss
src/components/templates/PostDetailTemplate/index.scss

Feat 302 error  bug

---

src/components/atoms/Loading/Loading.tsx
src/components/atoms/Loading/index.scss
src/components/atoms/Loading/index.stories.ts
src/components/organisms/FollowList/FollowList.tsx
src/components/organisms/UserDetailCard/section/Follows.tsx

관련 이슈: #
-
<br>
- 기존에 FollowList 바깥에서 Suspense를 걸어 둔 것을 안으로 옮겼습니다.
- dot 로딩을 추가했습니다.
-
<br>

✨ 팔로우리스트 리스트 컴포넌트 안에서 로딩 처리

---

src/components/atoms/Avatar/index.scss
src/components/organisms/CommentInput/index.scss
src/components/organisms/LikeDisLikeContainer/index.scss
src/components/templates/PostDetailTemplate/index.scss
src/hooks/useFollow.ts

관련 이슈: #
-
<br>
- 간격 조절
-
<br>

:tada: 디자인 수정

---

src/components/organisms/CommentInput/index.scss

관련 이슈: #
-
<br>
- 다크모드 시 댓글입력창에 색상 적용
-
<br>

✨ input입력창 색상변경

---

src/app/(root)/(routes)/post/[postId]/modify/page.tsx
src/app/api/post/[postId]/route.ts
src/app/api/posts/route.ts
src/app/api/posts/update/route.ts
src/app/api/users/route.ts
src/components/molcules/EditNamesForm/EditNamesform.tsx
src/components/organisms/LikeDisLikeContainer/LikeDIsLikeContainer.tsx
src/components/organisms/NavBar/UserList/HydratedUserList.tsx
src/components/organisms/NavBar/UserList/UserList.tsx
src/components/templates/ModifyPostPageTemplate/ModifyPostPageTemplate.tsx
src/hooks/useModifyPostForm.ts
src/queries/users/index.ts
src/services/post/index.ts

관련 이슈: #
- 좋아요 싫어요가 게시글 수정 후 안되는 문제가 있어서 수정했습니다.!!
- 60379eaae251668765b7e9c184c58df43e2d4ad9 이 커밋에 반영했습니다.!
- 더 꼼꼼히 예외처리를 했어야하는데... 너무 죄송해요..😢 
<br>
- 
-
<br>

🐛 게시글 수정 후 좋아요 싫어요 동작 안하는 문제 수정
